# Generated by Django 4.1 on 2022-09-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmini_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="transactions", name="user",),
        migrations.AddField(
            model_name="transactions",
            name="user_id",
            field=models.CharField(default="toyota", max_length=30),
            preserve_default=False,
        ),
    ]
