# Generated by Django 4.1 on 2022-09-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmini_app", "0002_remove_transactions_user_transactions_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderno", models.CharField(max_length=30)),
                ("partnumber", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=128)),
                ("totalqty", models.IntegerField(default=0)),
                ("qtyreceived", models.IntegerField(default=0)),
                ("qtyshort", models.IntegerField(default=0)),
                ("qtyextra", models.IntegerField(default=0)),
                ("qtydamanged", models.IntegerField(default=0)),
                ("linestatus", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="transactions",
            name="orderno",
            field=models.CharField(default="Hi", max_length=30),
            preserve_default=False,
        ),
    ]
