# Generated by Django 4.1 on 2022-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmini_app", "0004_inventory_stockvalue_productmaster_itemcode"),
    ]

    operations = [
        migrations.DeleteModel(name="StockValue",),
        migrations.AddField(
            model_name="inventory", name="profit", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventory",
            name="totalcost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventory",
            name="totalvalue",
            field=models.IntegerField(default=0),
        ),
    ]
