# Generated by Django 4.1 on 2022-09-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmini_app", "0005_delete_stockvalue_inventory_profit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory", name="profit", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="totalcost",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="totalvalue",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="productmaster",
            name="costprice",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="productmaster",
            name="saleprice",
            field=models.FloatField(default=0),
        ),
    ]
