# Generated by Django 4.1 on 2022-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmini_app", "0007_orderstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockorder",
            name="description",
            field=models.CharField(default="Inactive", max_length=128),
        ),
    ]
